version: '2'

services:

  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
      args:
        - ENV=${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - ALERT_POST_URL=${ALERT_POST_URL}
    restart: unless-stopped
    container_name: fabulate-node
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    ports:
      - 3030:3030
    volumes:
      - ./briefData:/app/briefData:rw
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    networks:
      - proxy-tier

  redis:
    build: ./docker/redis
    container_name: fabulate-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - proxy-tier

  postgres:
    build: ./docker/postgres
    container_name: fabulate-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'abc.123def'
      POSTGRES_USER: 'postgresabc'
      POSTGRES_DB: 'postgresdef'
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: server_default
