FROM node:carbon AS builder

WORKDIR /app
COPY ./lib ./lib

COPY package*.json ./
RUN npm i

COPY . .

RUN npm i && npm run build

FROM nginx:alpine

COPY ./docker/nginx /etc/nginx/conf.d

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
